from __future__ import annotations

from .constants import (
    AGENT_STATUSES,
    CITIES,
    CLAIM_STATUSES,
    CLAIM_TYPES,
    CUSTOMER_SEGMENTS,
    FIRST_NAMES,
    FRAUD_SCENARIOS,
    LAST_NAMES,
    POLICY_STATUSES,
    POLICY_TYPES,
    PREMIUM_STATUSES,
    SETTLEMENT_STATUSES,
)

__all__ = [
    "AGENT_STATUSES",
    "CITIES",
    "CLAIM_STATUSES",
    "CLAIM_TYPES",
    "CUSTOMER_SEGMENTS",
    "FIRST_NAMES",
    "FRAUD_SCENARIOS",
    "LAST_NAMES",
    "POLICY_STATUSES",
    "POLICY_TYPES",
    "PREMIUM_STATUSES",
    "SETTLEMENT_STATUSES",
]
