from __future__ import annotations

from .common import scenario

SCENARIOS = [
    scenario(domain="banking", scenario_id="banking_duplicate_transfer", name="Banking Duplicate Transfer", category="reconciliation", subcategory="transfer_deduplication", issue_type="duplicate_records", table="transfers", column="transfer_id", affected_tables=["deposit_accounts", "transfers", "payments"], validations=["duplicate_transfer_detected"], business_problem="Duplicate transfers can debit customers twice and break settlement reconciliation.", technical_problem="Selected transfer records are duplicated with deterministic targeting.", tags=["transfer", "duplicate", "settlement"], aliases=["duplicate transfer", "double transfer"]),
    scenario(domain="banking", scenario_id="banking_ledger_imbalance", name="Banking Ledger Imbalance", category="reconciliation", subcategory="ledger", issue_type="negative_values", table="payments", column="amount", affected_tables=["payments", "deposit_accounts"], validations=["ledger_imbalance_detected"], business_problem="Ledger imbalance creates financial reporting and operational risk.", technical_problem="Payment amounts are mutated to invalid negative values.", tags=["ledger", "imbalance", "payments"], aliases=["ledger imbalance"]),
    scenario(domain="banking", scenario_id="banking_missing_settlement", name="Banking Missing Settlement", category="batch_processing", subcategory="settlement", issue_type="missing_records", table="payments", column="payment_id", affected_tables=["payments", "transfers"], validations=["missing_settlement_detected"], business_problem="Missing settlement records leave transactions unresolved.", technical_problem="A controlled sample of payment rows is removed.", tags=["settlement", "missing"], aliases=["missing settlement"]),
    scenario(domain="banking", scenario_id="banking_fraud_burst", name="Banking Fraud Burst", category="fraud_risk", subcategory="transaction_monitoring", issue_type="outliers", table="payments", column="amount", affected_tables=["payments", "customers"], validations=["fraud_burst_detected"], business_problem="Bursts of suspicious high-value payments should trigger fraud controls.", technical_problem="Payment amount outliers are introduced at a controlled rate.", tags=["fraud", "burst", "outlier"], aliases=["fraud burst"]),
    scenario(domain="banking", scenario_id="banking_account_freeze", name="Banking Account Freeze", category="business_rule", subcategory="account_status", issue_type="foreign_key_break", table="transfers", column="source_account_id", affected_tables=["deposit_accounts", "transfers"], validations=["frozen_or_invalid_account_transfer_detected"], business_problem="Frozen or invalid accounts should not initiate successful transfers.", technical_problem="Transfer source account references are changed to nonexistent IDs.", tags=["account", "freeze", "referential"], aliases=["account freeze"]),
]
