from __future__ import annotations

from .common import scenario

SCENARIOS = [
    scenario(domain="ecommerce", scenario_id="ecommerce_payment_retry", name="E-commerce Payment Retry", category="reconciliation", subcategory="payment_idempotency", issue_type="duplicate_records", table="payments", column="payment_id", affected_tables=["orders", "payments"], validations=["payment_retry_duplicate_detected"], business_problem="Payment retries can create duplicate charges or inconsistent order state.", technical_problem="Payment rows are duplicated to test idempotency handling.", tags=["payment", "retry", "idempotency"], aliases=["marketplace payment retry"]),
    scenario(domain="ecommerce", scenario_id="ecommerce_cart_abandonment", name="E-commerce Cart Abandonment", category="batch_processing", subcategory="funnel", issue_type="missing_records", table="orders", column="order_id", affected_tables=["carts", "orders"], validations=["cart_abandonment_detected"], business_problem="Cart abandonment and missing order conversion can skew funnel analytics.", technical_problem="Selected downstream order rows are removed.", tags=["cart", "funnel", "abandonment"], aliases=["cart abandonment"]),
    scenario(domain="ecommerce", scenario_id="ecommerce_inventory_oversell", name="E-commerce Inventory Oversell", category="business_rule", subcategory="inventory", issue_type="negative_values", table="product_listings", column="available_quantity", affected_tables=["product_listings", "orders", "order_items"], validations=["inventory_oversell_detected"], business_problem="Overselling inventory creates fulfillment failures and refunds.", technical_problem="Listing availability is mutated to invalid negative values.", tags=["inventory", "oversell"], aliases=["inventory oversell"]),
    scenario(domain="ecommerce", scenario_id="ecommerce_refund_failure", name="E-commerce Refund Failure", category="reconciliation", subcategory="refunds", issue_type="missing_records", table="returns", column="return_id", affected_tables=["orders", "payments", "returns"], validations=["refund_failure_detected"], business_problem="Refund failures create customer-service and accounting issues.", technical_problem="Return/refund records are removed from selected downstream flow.", tags=["refund", "return"], aliases=["refund failure"]),
    scenario(domain="ecommerce", scenario_id="ecommerce_order_status_mismatch", name="E-commerce Order Status Mismatch", category="temporal_sequence", subcategory="order_lifecycle", issue_type="datatype_mismatch", table="orders", column="order_status", affected_tables=["orders", "shipments", "payments"], validations=["order_status_mismatch_detected"], business_problem="Order status mismatches break fulfillment and customer notifications.", technical_problem="Order status values are changed to invalid types.", tags=["order", "status"], aliases=["order status mismatch"]),
]
