from __future__ import annotations

from .common import scenario

SCENARIOS = [
    scenario(domain="education", scenario_id="education_attendance_drop", name="Education Attendance Drop", category="operational_failure", subcategory="attendance", issue_type="outliers", table="attendance", column="attendance_percentage", affected_tables=["students", "enrollments", "attendance"], validations=["attendance_drop_detected"], business_problem="Attendance drops can predict retention and performance issues.", technical_problem="Attendance percentages are mutated into outliers.", tags=["attendance", "drop"], aliases=["attendance drop"]),
    scenario(domain="education", scenario_id="education_duplicate_enrollment", name="Education Duplicate Enrollment", category="data_quality", subcategory="duplicates", issue_type="duplicate_records", table="enrollments", column="enrollment_id", affected_tables=["students", "enrollments"], validations=["duplicate_enrollment_detected"], business_problem="Duplicate enrollments inflate headcount, credits, and billing.", technical_problem="Enrollment rows are duplicated at controlled rates.", tags=["enrollment", "duplicate"], aliases=["duplicate enrollment"]),
    scenario(domain="education", scenario_id="education_grade_calculation_error", name="Education Grade Calculation Error", category="business_rule", subcategory="gradebook", issue_type="negative_values", table="examination_results", column="marks_obtained", affected_tables=["assignment_submissions", "examination_results", "enrollments"], validations=["grade_calculation_error_detected"], business_problem="Incorrect grade calculations affect academic standing and progression.", technical_problem="Marks are changed to invalid negative values.", tags=["grade", "calculation"], aliases=["grade error"]),
    scenario(domain="education", scenario_id="education_fee_hold", name="Education Fee Hold", category="business_rule", subcategory="fees", issue_type="negative_values", table="fees_payments", column="amount_paid", affected_tables=["students", "fees_payments"], validations=["fee_hold_detected"], business_problem="Fee holds should prevent registration when balances are unresolved.", technical_problem="Fee payment amounts are changed to invalid negative values.", tags=["fee", "hold"], aliases=["fee hold"]),
    scenario(domain="education", scenario_id="education_graduation_eligibility_failure", name="Education Graduation Eligibility Failure", category="reconciliation", subcategory="graduation", issue_type="datatype_mismatch", table="enrollments", column="final_grade", affected_tables=["enrollments", "examination_results"], validations=["graduation_eligibility_failure_detected"], business_problem="Graduation eligibility errors affect degree auditing and reporting.", technical_problem="Final grades are changed to invalid values.", tags=["graduation", "eligibility"], aliases=["graduation eligibility"]),
]

