from __future__ import annotations

from .common import scenario

SCENARIOS = [
    scenario(domain="finance", scenario_id="finance_month_end_spike", name="Finance Month-End Spike", category="performance", subcategory="month_end", issue_type="outliers", table="transactions", column="transaction_amount", affected_tables=["accounts", "transactions"], validations=["month_end_spike_detected"], business_problem="Month-end spikes can stress reconciliation and risk systems.", technical_problem="Transaction amount outliers create controlled volume/value pressure.", tags=["month_end", "spike"], aliases=["month end spike"]),
    scenario(domain="finance", scenario_id="finance_duplicate_trade", name="Finance Duplicate Trade", category="data_quality", subcategory="duplicates", issue_type="duplicate_records", table="transactions", column="transaction_id", affected_tables=["accounts", "transactions"], validations=["duplicate_trade_detected"], business_problem="Duplicate trades distort positions, fees, and risk.", technical_problem="Transaction rows are duplicated at controlled rates.", tags=["trade", "duplicate"], aliases=["duplicate trade"]),
    scenario(domain="finance", scenario_id="finance_currency_conversion_error", name="Finance Currency Conversion Error", category="reconciliation", subcategory="currency", issue_type="datatype_mismatch", table="transactions", column="transaction_amount", affected_tables=["accounts", "transactions"], validations=["currency_conversion_error_detected"], business_problem="Currency conversion errors break financial reconciliation.", technical_problem="Transaction amounts receive invalid datatype mutations.", tags=["currency", "conversion"], aliases=["currency conversion error"]),
    scenario(domain="finance", scenario_id="finance_settlement_delay", name="Finance Settlement Delay", category="temporal_sequence", subcategory="settlement", issue_type="invalid_dates", table="transactions", column="transaction_timestamp", affected_tables=["transactions"], validations=["settlement_delay_detected"], business_problem="Settlement delays affect cash availability and position reporting.", technical_problem="Transaction timestamps are moved to invalid/future values.", tags=["settlement", "delay"], aliases=["settlement delay"]),
    scenario(domain="finance", scenario_id="finance_fee_miscalculation", name="Finance Fee Miscalculation", category="business_rule", subcategory="fees", issue_type="negative_values", table="transactions", column="transaction_amount", affected_tables=["transactions"], validations=["fee_miscalculation_detected"], business_problem="Fee miscalculations affect revenue, client billing, and reconciliation.", technical_problem="Transaction values are mutated into invalid negative amounts.", tags=["fee", "miscalculation"], aliases=["fee error"]),
]

