from __future__ import annotations

from .common import scenario

SCENARIOS = [
    scenario(domain="healthcare", scenario_id="healthcare_ghost_provider", name="Healthcare Ghost Provider", category="referential_integrity", subcategory="provider_claims", issue_type="foreign_key_break", table="claims", column="provider_id", affected_tables=["providers", "visits", "claims"], validations=["orphan_provider_detected"], business_problem="Claims referencing nonexistent providers can cause billing and compliance failures.", technical_problem="Provider foreign keys are replaced with valid-looking nonexistent identifiers.", tags=["provider", "claim", "fk"], aliases=["ghost provider", "orphan provider"]),
    scenario(domain="healthcare", scenario_id="healthcare_duplicate_claim", name="Healthcare Duplicate Claim", category="data_quality", subcategory="duplicates", issue_type="duplicate_records", table="claims", column="claim_id", affected_tables=["claims", "payments"], validations=["duplicate_claim_detected"], business_problem="Duplicate claims can overstate receivables or trigger duplicate reimbursements.", technical_problem="Claims are duplicated at a controlled rate.", tags=["claim", "duplicate"], aliases=["duplicate claim"]),
    scenario(domain="healthcare", scenario_id="healthcare_missing_diagnosis", name="Healthcare Missing Diagnosis", category="business_rule", subcategory="clinical_coding", issue_type="missing_records", table="diagnoses", column="diagnosis_id", affected_tables=["visits", "diagnoses", "procedures"], validations=["missing_diagnosis_detected"], business_problem="Visits without diagnoses can fail coding, analytics, and claim adjudication.", technical_problem="Diagnosis rows are removed for selected visits.", tags=["diagnosis", "coding", "missing"], aliases=["missing diagnosis"]),
    scenario(domain="healthcare", scenario_id="healthcare_late_insurance_approval", name="Healthcare Late Insurance Approval", category="temporal_sequence", subcategory="claim_lifecycle", issue_type="invalid_dates", table="claims", column="submitted_date", affected_tables=["claims", "payments"], validations=["late_approval_sequence_detected"], business_problem="Late approvals distort receivables aging and patient billing timelines.", technical_problem="Claim submission dates are changed to invalid/future values.", tags=["approval", "late", "claims"], aliases=["late approval"]),
    scenario(domain="healthcare", scenario_id="healthcare_invalid_procedure", name="Healthcare Invalid Procedure", category="business_rule", subcategory="procedure_coding", issue_type="datatype_mismatch", table="procedures", column="cpt_code", affected_tables=["diagnoses", "procedures"], validations=["invalid_procedure_detected"], business_problem="Invalid procedure codes break claim adjudication and clinical analytics.", technical_problem="Procedure code values are replaced with invalid datatypes.", tags=["cpt", "procedure", "coding"], aliases=["invalid procedure"]),
]

