from __future__ import annotations

from .common import scenario

SCENARIOS = [
    scenario(domain="insurance", scenario_id="insurance_suspicious_claim", name="Insurance Suspicious Claim", category="fraud_risk", subcategory="claims", issue_type="outliers", table="claims", column="claim_amount", affected_tables=["policies", "claims", "settlements"], validations=["suspicious_claim_detected"], business_problem="Suspicious claims should trigger fraud review without blocking clean claims.", technical_problem="Claim amount outliers are introduced at a controlled rate.", tags=["claim", "fraud", "outlier"], aliases=["suspicious claim"]),
    scenario(domain="insurance", scenario_id="insurance_duplicate_claim", name="Insurance Duplicate Claim", category="data_quality", subcategory="duplicates", issue_type="duplicate_records", table="claims", column="claim_id", affected_tables=["claims", "settlements"], validations=["duplicate_claim_detected"], business_problem="Duplicate claims can create duplicate reserves or payouts.", technical_problem="Claim rows are duplicated deterministically.", tags=["claim", "duplicate"], aliases=["duplicate insurance claim"]),
    scenario(domain="insurance", scenario_id="insurance_coverage_exceeded", name="Insurance Coverage Exceeded", category="business_rule", subcategory="coverage", issue_type="outliers", table="claims", column="claim_amount", affected_tables=["policies", "claims"], validations=["coverage_exceeded_detected"], business_problem="Claim amounts above coverage should be rejected or flagged.", technical_problem="Claim amounts are inflated beyond expected range.", tags=["coverage", "claim"], aliases=["coverage exceeded"]),
    scenario(domain="insurance", scenario_id="insurance_renewal_failure", name="Insurance Renewal Failure", category="temporal_sequence", subcategory="renewal", issue_type="invalid_dates", table="policies", column="policy_end_date", affected_tables=["policies", "premiums"], validations=["renewal_failure_detected"], business_problem="Renewal failures can leave customers incorrectly uninsured or billed.", technical_problem="Policy end dates are changed to invalid/future values.", tags=["renewal", "policy"], aliases=["renewal failure"]),
    scenario(domain="insurance", scenario_id="insurance_premium_miscalculation", name="Insurance Premium Miscalculation", category="reconciliation", subcategory="premium", issue_type="negative_values", table="premiums", column="premium_amount", affected_tables=["policies", "premiums"], validations=["premium_miscalculation_detected"], business_problem="Premium miscalculations distort billing and policy profitability.", technical_problem="Premium amounts are changed to invalid negative values.", tags=["premium", "billing"], aliases=["premium error"]),
]

