from __future__ import annotations

from .common import scenario

SCENARIOS = [
    scenario(domain="logistics", scenario_id="logistics_gps_jump", name="Logistics GPS Jump", category="temporal_sequence", subcategory="tracking", issue_type="outliers", table="gps_events", column="latitude", affected_tables=["shipments", "gps_events", "tracking_events"], validations=["gps_jump_detected"], business_problem="GPS jumps can break route tracking and ETA prediction.", technical_problem="GPS latitude values are mutated into unrealistic outliers.", tags=["gps", "tracking"], aliases=["gps jump"]),
    scenario(domain="logistics", scenario_id="logistics_late_delivery", name="Logistics Late Delivery", category="temporal_sequence", subcategory="delivery_sla", issue_type="invalid_dates", table="tracking_events", column="event_timestamp", affected_tables=["shipments", "tracking_events"], validations=["late_delivery_detected"], business_problem="Late deliveries affect SLA reporting and customer notifications.", technical_problem="Tracking timestamps are changed to invalid/future sequence values.", tags=["late", "delivery", "sla"], aliases=["late delivery"]),
    scenario(domain="logistics", scenario_id="logistics_lost_shipment", name="Logistics Lost Shipment", category="operational_failure", subcategory="lost_package", issue_type="missing_records", table="tracking_events", column="event_id", affected_tables=["shipments", "tracking_events"], validations=["lost_shipment_detected"], business_problem="Missing tracking events make shipments appear lost or stalled.", technical_problem="Selected tracking event rows are removed.", tags=["lost", "shipment", "missing"], aliases=["lost shipment"]),
    scenario(domain="logistics", scenario_id="logistics_customs_delay", name="Logistics Customs Delay", category="batch_processing", subcategory="customs", issue_type="invalid_dates", table="shipments", column="created_at", affected_tables=["shipments", "tracking_events"], validations=["customs_delay_detected"], business_problem="Customs delays affect international ETA and exception workflows.", technical_problem="Shipment dates are changed to invalid/future values.", tags=["customs", "delay"], aliases=["customs delay"]),
    scenario(domain="logistics", scenario_id="logistics_cold_chain_failure", name="Logistics Cold Chain Failure", category="business_rule", subcategory="temperature_compliance", issue_type="outliers", table="delivery_records", column="delivery_time_minutes", affected_tables=["shipments", "delivery_records"], validations=["temperature_breach_detected", "cold_chain_compliance_failed"], business_problem="Temperature breaches can spoil cold-chain shipments.", technical_problem="Delivery duration outliers stand in for delayed cold-chain exposure in the current schema.", tags=["cold_chain", "temperature"], aliases=["cold chain failure"]),
]
