from __future__ import annotations

from .common import scenario

SCENARIOS = [
    scenario(domain="manufacturing", scenario_id="manufacturing_defect_spike", name="Manufacturing Defect Spike", category="operational_failure", subcategory="quality", issue_type="outliers", table="quality_checks", column="defect_count", affected_tables=["production_batches", "quality_checks"], validations=["defect_spike_detected"], business_problem="Sudden defect spikes should trigger quality containment and root-cause analysis.", technical_problem="Quality defect counts are mutated into outliers.", tags=["defect", "quality", "spike"], aliases=["defect spike"]),
    scenario(domain="manufacturing", scenario_id="manufacturing_machine_downtime", name="Manufacturing Machine Downtime", category="operational_failure", subcategory="equipment", issue_type="outliers", table="maintenance_orders", column="downtime_minutes", affected_tables=["machines", "maintenance_orders", "work_orders"], validations=["downtime_spike_detected"], business_problem="Machine downtime reduces capacity and delays production.", technical_problem="Downtime durations are increased as controlled outliers.", tags=["machine", "downtime"], aliases=["machine downtime"]),
    scenario(domain="manufacturing", scenario_id="manufacturing_missing_quality_inspection", name="Manufacturing Missing Quality Inspection", category="business_rule", subcategory="quality_gate", issue_type="missing_records", table="quality_checks", column="quality_check_id", affected_tables=["production_batches", "quality_checks"], validations=["missing_quality_inspection_detected"], business_problem="Missing inspection records can allow unverified batches downstream.", technical_problem="Inspection rows are removed for selected production batches.", tags=["inspection", "quality", "missing"], aliases=["missing inspection"]),
    scenario(domain="manufacturing", scenario_id="manufacturing_capacity_overflow", name="Manufacturing Capacity Overflow", category="performance", subcategory="capacity", issue_type="outliers", table="production_batches", column="quantity_produced", affected_tables=["production_lines", "production_batches"], validations=["capacity_overflow_detected"], business_problem="Production quantities above line capacity should be flagged.", technical_problem="Batch quantities are inflated beyond expected range.", tags=["capacity", "overflow"], aliases=["capacity overflow"]),
    scenario(domain="manufacturing", scenario_id="manufacturing_maintenance_delay", name="Manufacturing Maintenance Delay", category="temporal_sequence", subcategory="maintenance", issue_type="invalid_dates", table="maintenance_orders", column="scheduled_time", affected_tables=["machines", "maintenance_orders"], validations=["maintenance_delay_detected"], business_problem="Delayed maintenance increases downtime and quality risk.", technical_problem="Maintenance dates are moved to invalid/future values.", tags=["maintenance", "delay"], aliases=["maintenance delay"]),
]
