from __future__ import annotations

from .common import scenario

SCENARIOS = [
    scenario(domain="retail", scenario_id="retail_payment_retry", name="Retail Payment Retry", category="reconciliation", subcategory="payment_idempotency", issue_type="duplicate_records", table="payments", column="payment_id", affected_tables=["sales", "payments"], validations=["duplicate_payment_detected", "payment_reconciliation_failed"], business_problem="Payment retries can double-count revenue or create duplicate captures.", technical_problem="Duplicate payment rows are introduced at a controlled rate while preserving deterministic locators.", tags=["payment", "retry", "idempotency"], aliases=["payment retry", "duplicate payment"]),
    scenario(domain="retail", scenario_id="retail_duplicate_order", name="Retail Duplicate Order", category="data_quality", subcategory="duplicates", issue_type="duplicate_records", table="sales", column="sale_id", affected_tables=["sales", "payments"], validations=["duplicate_order_detected"], business_problem="Duplicate orders inflate demand, revenue, and downstream fulfillment.", technical_problem="Selected sales rows are duplicated to test deduplication and primary-key validation.", tags=["order", "duplicate"], aliases=["duplicate order", "duplicate sale"]),
    scenario(domain="retail", scenario_id="retail_inventory_mismatch", name="Retail Inventory Mismatch", category="reconciliation", subcategory="inventory", issue_type="negative_values", table="inventory", column="quantity_on_hand", affected_tables=["inventory", "products", "sales"], validations=["inventory_reconciliation_failed"], business_problem="Inventory counts can become negative or inconsistent after sales and returns.", technical_problem="Inventory quantity values are mutated to invalid negative values.", tags=["inventory", "stock", "reconciliation"], aliases=["inventory mismatch", "stock mismatch"]),
    scenario(domain="retail", scenario_id="retail_promotion_price_error", name="Retail Promotion Price Error", category="business_rule", subcategory="pricing", issue_type="outliers", table="sales", column="sale_amount", affected_tables=["sales", "promotions", "products"], validations=["price_outlier_detected"], business_problem="Promotion pricing errors can undercharge or overcharge customers.", technical_problem="Sale amount outliers are introduced to exercise pricing validation.", tags=["promotion", "pricing", "outlier"], aliases=["promotion error", "price error"]),
    scenario(domain="retail", scenario_id="retail_late_shipment", name="Retail Late Shipment", category="temporal_sequence", subcategory="fulfillment", issue_type="invalid_dates", table="sales", column="sale_timestamp", affected_tables=["sales"], validations=["late_or_invalid_shipment_timing_detected"], business_problem="Late fulfillment disrupts customer experience and SLA reporting.", technical_problem="Invalid/future timing values are introduced in the sales timeline.", tags=["shipment", "late", "temporal"], aliases=["late shipment", "delayed order"]),
]

